import { WilayaStatus } from "../src/types.js";

// v2.3.0 (simulation purge): this file used to ship 7 fabricated citizen
// reports (fake AI verification, fake consensus, fake official badge codes),
// 6 fabricated satellite hotspots, and fake active-fire counts on 7 wilayas.
// They were auto-seeded into Firestore on first boot and served as "fallback"
// data on 4 routes — meaning a real operator could see fake critical fires,
// fake hotspots and fake rescue teams on a live incident. All of it is gone.
// What remains is the static wilaya REGISTRY: names + emergency phone numbers
// — reference data only. Every dynamic field (activeFires, satelliteHotspots,
// severity, evacuationRecommended) is now computed exclusively from live
// reports and live NASA FIRMS data; the stored values below are inert zeros
// kept so the type stays satisfiable without a default-object trick.
export const wilayasStatus: WilayaStatus[] = [
  { nameAr: "الجزائر - أدرار", nameFr: "Algérie - Adrar", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الشلف", nameFr: "Algérie - Chlef", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الأغواط", nameFr: "Algérie - Laghouat", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - أم البواقي", nameFr: "Algérie - Oum El Bouaghi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - باتنة", nameFr: "Algérie - Batna", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بجاية", nameFr: "Algérie - Béjaïa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بسكرة", nameFr: "Algérie - Biskra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بشار", nameFr: "Algérie - Béchar", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - البليدة", nameFr: "Algérie - Blida", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - البويرة", nameFr: "Algérie - Bouira", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تمنراست", nameFr: "Algérie - Tamanrasset", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تبسة", nameFr: "Algérie - Tébessa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تلمسان", nameFr: "Algérie - Tlemcen", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيارت", nameFr: "Algérie - Tiaret", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيزي وزو", nameFr: "Algérie - Tizi Ouzou", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الجزائر العاصمة", nameFr: "Algérie - Alger", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الجلفة", nameFr: "Algérie - Djelfa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - جيجل", nameFr: "Algérie - Jijel", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سطيف", nameFr: "Algérie - Sétif", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سعيدة", nameFr: "Algérie - Saïda", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سكيكدة", nameFr: "Algérie - Skikda", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سيدي بلعباس", nameFr: "Algérie - Sidi Bel Abbès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عنابة", nameFr: "Algérie - Annaba", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - قالمة", nameFr: "Algérie - Guelma", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - قسنطينة", nameFr: "Algérie - Constantine", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - المدية", nameFr: "Algérie - Médéa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - مستغانم", nameFr: "Algérie - Mostaganem", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - المسيلة", nameFr: "Algérie - M'Sila", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - معسكر", nameFr: "Algérie - Mascara", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - ورقلة", nameFr: "Algérie - Ouargla", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - وهران", nameFr: "Algérie - Oran", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - البيض", nameFr: "Algérie - El Bayadh", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - إليزي", nameFr: "Algérie - Illizi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - برج بوعريريج", nameFr: "Algérie - Bordj Bou Arréridj", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بومرداس", nameFr: "Algérie - Boumerdès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الطارف", nameFr: "Algérie - El Tarf", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تندوف", nameFr: "Algérie - Tindouf", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيسمسيلت", nameFr: "Algérie - Tissemsilt", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الوادي", nameFr: "Algérie - El Oued", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - خنشلة", nameFr: "Algérie - Khenchela", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سوق أهراس", nameFr: "Algérie - Souk Ahras", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيبازة", nameFr: "Algérie - Tipaza", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - ميلة", nameFr: "Algérie - Mila", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عين الدفلى", nameFr: "Algérie - Aïn Defla", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - النعامة", nameFr: "Algérie - Naâma", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عين تموشنت", nameFr: "Algérie - Aïn Témouchent", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - غرداية", nameFr: "Algérie - Ghardaïa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - غليزان", nameFr: "Algérie - Relizane", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيميمون", nameFr: "Algérie - Timimoun", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - برج باجي مختار", nameFr: "Algérie - Bordj Badji Mokhtar", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - أولاد جلال", nameFr: "Algérie - Ouled Djellal", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بني عباس", nameFr: "Algérie - Béni Abbès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عين صالح", nameFr: "Algérie - In Salah", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عين قزام", nameFr: "Algérie - In Guezzam", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تقرت", nameFr: "Algérie - Touggourt", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - جانت", nameFr: "Algérie - Djanet", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - المغير", nameFr: "Algérie - El M'Ghair", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - المنيعة", nameFr: "Algérie - El Meniaa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "تونس - جندوبة", nameFr: "Tunisie - Jendouba", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - باجة", nameFr: "Tunisie - Béja", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - بنزرت", nameFr: "Tunisie - Bizerte", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - تونس العاصمة", nameFr: "Tunisie - Tunis", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - أريانة", nameFr: "Tunisie - Ariana", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - بن عروس", nameFr: "Tunisie - Ben Arous", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - منوبة", nameFr: "Tunisie - Manouba", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - نابل", nameFr: "Tunisie - Nabeul", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - زغوان", nameFr: "Tunisie - Zaghouan", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - الكاف", nameFr: "Tunisie - Le Kef", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - سليانة", nameFr: "Tunisie - Siliana", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - سوسة", nameFr: "Tunisie - Sousse", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - المنستير", nameFr: "Tunisie - Monastir", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - المهدية", nameFr: "Tunisie - Mahdia", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - صفاقس", nameFr: "Tunisie - Sfax", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - القيروان", nameFr: "Tunisie - Kairouan", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - القصرين", nameFr: "Tunisie - Kasserine", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - سيدي بوزيد", nameFr: "Tunisie - Sidi Bouzid", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - قابس", nameFr: "Tunisie - Gabès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - مدنين", nameFr: "Tunisie - Medenine", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - تطاوين", nameFr: "Tunisie - Tataouine", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - قفصة", nameFr: "Tunisie - Gafsa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - توزر", nameFr: "Tunisie - Tozeur", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - قبلي", nameFr: "Tunisie - Kebili", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "المغرب - طنجة تطوان الحسيمة", nameFr: "Maroc - Tanger-Tétouan", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - الشرقية", nameFr: "Maroc - L'Oriental", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - فاس مكناس", nameFr: "Maroc - Fès-Meknès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - الرباط سلا القنيطرة", nameFr: "Maroc - Rabat-Salé-Kénitra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - بني ملال خنيفرة", nameFr: "Maroc - Béni Mellal-Khénifra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - الدار البيضاء سطات", nameFr: "Maroc - Casablanca-Settat", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - مراكش آسفي", nameFr: "Maroc - Marrakech-Safi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - درعة تافيلالت", nameFr: "Maroc - Drâa-Tafilalet", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - سوس ماسة", nameFr: "Maroc - Souss-Massa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - كلميم واد نون", nameFr: "Maroc - Guelmim-Oued Noun", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - العيون الساقية الحمراء", nameFr: "Maroc - Laâyoune-Sakia El Hamra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - الداخلة وادي الذهب", nameFr: "Maroc - Dakhla-Oued Ed-Dahab", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "ليبيا - الجبل الأخضر", nameFr: "Libye - Al Jabal al Akhdar", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - طرابلس", nameFr: "Libye - Tripoli", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - بنغازي", nameFr: "Libye - Benghazi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - مصراتة", nameFr: "Libye - Misrata", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الزاوية", nameFr: "Libye - Zawiya", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - سبها", nameFr: "Libye - Sabha", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - سرت", nameFr: "Libye - Sirte", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - طبرق", nameFr: "Libye - Tobruk", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - درنة", nameFr: "Libye - Derna", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - المرج", nameFr: "Libye - Al Marj", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الواحات", nameFr: "Libye - Al Wahat", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الكفرة", nameFr: "Libye - Al Kufra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - مرزق", nameFr: "Libye - Murzuq", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - غات", nameFr: "Libye - Ghat", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - وادي الحياة", nameFr: "Libye - Wadi al Hayaa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - وادي الشاطئ", nameFr: "Libye - Wadi al Shatii", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الجفرة", nameFr: "Libye - Al Jufra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الجبل الغربي", nameFr: "Libye - Jabal al Gharbi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - نالوت", nameFr: "Libye - Nalut", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - النقاط الخمس", nameFr: "Libye - Nuqat al Khams", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الجفارة", nameFr: "Libye - Al Jfara", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - المرقب", nameFr: "Libye - Al Murgub", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
];
