import { Report, SatelliteHotspot, WilayaStatus } from "../src/types.js";

export const citizenReports: Report[] = [
  {
    id: "rep-1", lat: 36.881, lng: 8.412,
    locationName: "بالقرب من بحيرة طونغا، القالة",
    wilaya: "الجزائر - الطارف (Algérie - El Tarf)",
    description: "النيران تنتشر بسرعة في أحراش البلوط، الرياح قوية ونناشد الحماية المدنية بالتدخل الطائرات ضرورية هنا.",
    severity: "critical", status: "verified",
    timestamp: "2026-07-21T11:30:00Z", consensusCount: 15,
    reporterType: "official", reporterBadgeCode: "1021",
    aiVerification: {
      isVerified: true, confidence: 95,
      detectedSigns: ["ألسنة لهب كثيفة", "دخان أسود كثيف", "غابات الصنوبر"],
      aiComments: "يُظهر التحليل البصري خط حريق نشط في منطقة غابية كثيفة مع انبعاثات دخانية تهدد الغطاء النباتي.",
      suggestedSeverity: "CRITICAL",
    },
  },
  {
    id: "rep-2", lat: 36.835, lng: 6.635,
    locationName: "أعالي تمالوس، غابة بئر حداد",
    wilaya: "الجزائر - سكيكدة (Algérie - Skikda)",
    description: "دخان كثيف يتصاعد من وسط الغابة. الحريق بدأ قبل نصف ساعة ويتسع الآن.",
    severity: "high", status: "verified",
    timestamp: "2026-07-21T11:45:00Z", consensusCount: 8,
    reporterType: "volunteer", reporterBadgeCode: "777",
    aiVerification: {
      isVerified: true, confidence: 88,
      detectedSigns: ["أعمدة دخان أبيض ورمادي", "غطاء غابي كثيف"],
      aiComments: "تأكيد تصاعد أعمدة دخان مميزة لحرائق الغابات في المراحل الأولى.",
      suggestedSeverity: "HIGH",
    },
  },
  {
    id: "rep-3", lat: 36.911, lng: 7.675,
    locationName: "طريق سرايدي الجبلي",
    wilaya: "الجزائر - عنابة (Algérie - Annaba)",
    description: "اندلاع حريق جانبي بجوار الطريق الجبلي سرايدي، نرجو الحذر من السائقين وتجنب الصعود حاليا.",
    severity: "medium", status: "pending",
    timestamp: "2026-07-21T12:15:00Z", consensusCount: 3,
    reporterType: "citizen",
  },
  {
    id: "rep-4", lat: 36.721, lng: 4.041,
    locationName: "أعالي الأربعاء نايث إيراثن",
    wilaya: "الجزائر - تيزي وزو (Algérie - Tizi Ouzou)",
    description: "نشوب بؤرة حريق صغيرة قرب الأحواش السكنية، الشباب هنا يقومون بمحاصرتها بالمياه والتراب، الحماية المدنية في طريقها للمكان.",
    severity: "high", status: "verified",
    timestamp: "2026-07-21T12:05:00Z", consensusCount: 11,
    reporterType: "volunteer", reporterBadgeCode: "888",
    aiVerification: {
      isVerified: true, confidence: 90,
      detectedSigns: ["أعمدة لهب نشطة", "قرب مجمعات سكنية"],
      aiComments: "تم رصد الحريق بالقرب من تجمعات سكنية جبلية جراء ارتفاع حرارة الجو، يوصى بمتابعة سريعة.",
      suggestedSeverity: "HIGH",
    },
  },
  {
    id: "rep-tn-1", lat: 36.782, lng: 8.685,
    locationName: "عين دراهم الجبلية",
    wilaya: "تونس - جندوبة (Tunisie - Jendouba)",
    description: "حريق غابي نشط في مرتفعات عين دراهم، فرق الإطفاء تحاول السيطرة عليه لمنع تمدده للمناطق المجاورة.",
    severity: "critical", status: "verified",
    timestamp: "2026-07-21T12:20:00Z", consensusCount: 14,
    reporterType: "official", reporterBadgeCode: "198",
    aiVerification: {
      isVerified: true, confidence: 96,
      detectedSigns: ["لهب ممتد", "غابة صنوبر جبلية"],
      aiComments: "مصادقة بصرية كاملة لحريق غابي ممتد على المرتفعات الشمالية الغربية لتونس.",
      suggestedSeverity: "CRITICAL",
    },
  },
  {
    id: "rep-ma-1", lat: 35.612, lng: -5.275,
    locationName: "غابة باب تازة بمحيط شفشاون",
    wilaya: "المغرب - طنجة تطوان الحسيمة (Maroc - Tanger-Tétouan)",
    description: "دخان مرئي من وسط غابة باب تازة الجبلية. السكان المحليون يشاركون في جهود الإطفاء والاحتواء.",
    severity: "high", status: "verified",
    timestamp: "2026-07-21T11:55:00Z", consensusCount: 12,
    reporterType: "volunteer", reporterBadgeCode: "150",
    aiVerification: {
      isVerified: true, confidence: 91,
      detectedSigns: ["سحب دخان كثيف", "تضاريس غابية جبلية"],
      aiComments: "تم رصد دخان كثيف متصاعد من تضاريس وعرة في جبال الريف المغربية.",
      suggestedSeverity: "HIGH",
    },
  },
  {
    id: "rep-ly-1", lat: 32.745, lng: 21.841,
    locationName: "مرتفعات شحات الغابية",
    wilaya: "ليبيا - الجبل الأخضر (Libye - Al Jabal al Akhdar)",
    description: "تصاعد أعمدة دخان من الأحراش القريبة من غابات شحات بالجبل الأخضر، نسأل الله السلامة واللطف.",
    severity: "medium", status: "pending",
    timestamp: "2026-07-21T12:10:00Z", consensusCount: 4,
    reporterType: "citizen",
  },
];

export const satelliteHotspots: SatelliteHotspot[] = [
  { id: "sat-1", lat: 36.885, lng: 8.423, brightness: 345.5, confidence: 92, scanTime: "2026-08-08T10:15:00Z", satellite: "VIIRS", wilaya: "الجزائر - الطارف (Algérie - El Tarf)" },
  { id: "sat-2", lat: 36.892, lng: 8.451, brightness: 332.1, confidence: 85, scanTime: "2026-08-08T10:15:00Z", satellite: "VIIRS", wilaya: "الجزائر - الطارف (Algérie - El Tarf)" },
  { id: "sat-3", lat: 36.842, lng: 6.641, brightness: 328.4, confidence: 89, scanTime: "2026-08-08T11:02:00Z", satellite: "MODIS", wilaya: "الجزائر - سكيكدة (Algérie - Skikda)" },
  { id: "sat-tn-1", lat: 36.650, lng: 8.780, brightness: 348.6, confidence: 94, scanTime: "2026-08-08T12:00:00Z", satellite: "VIIRS", wilaya: "تونس - جندوبة (Tunisie - Jendouba)" },
  { id: "sat-ma-1", lat: 35.580, lng: -5.360, brightness: 339.2, confidence: 91, scanTime: "2026-08-08T11:50:00Z", satellite: "MODIS", wilaya: "المغرب - طنجة تطوان الحسيمة (Maroc - Tanger-Tétouan)" },
  { id: "sat-ly-1", lat: 32.750, lng: 21.850, brightness: 341.0, confidence: 93, scanTime: "2026-08-08T11:40:00Z", satellite: "VIIRS", wilaya: "ليبيا - الجبل الأخضر (Libye - Al Jabal al Akhdar)" },
];

export const wilayasStatus: WilayaStatus[] = [
  { nameAr: "الجزائر - أدرار", nameFr: "Algérie - Adrar", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الشلف", nameFr: "Algérie - Chlef", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الأغواط", nameFr: "Algérie - Laghouat", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - أم البواقي", nameFr: "Algérie - Oum El Bouaghi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - باتنة", nameFr: "Algérie - Batna", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بجاية", nameFr: "Algérie - Béjaïa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بسكرة", nameFr: "Algérie - Biskra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بشار", nameFr: "Algérie - Béchar", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - البليدة", nameFr: "Algérie - Blida", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - البويرة", nameFr: "Algérie - Bouira", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تمنراست", nameFr: "Algérie - Tamanrasset", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تبسة", nameFr: "Algérie - Tébessa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تلمسان", nameFr: "Algérie - Tlemcen", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيارت", nameFr: "Algérie - Tiaret", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيزي وزو", nameFr: "Algérie - Tizi Ouzou", activeFires: 1, satelliteHotspots: 0, severity: "high", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الجزائر العاصمة", nameFr: "Algérie - Alger", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الجلفة", nameFr: "Algérie - Djelfa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - جيجل", nameFr: "Algérie - Jijel", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سطيف", nameFr: "Algérie - Sétif", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سعيدة", nameFr: "Algérie - Saïda", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سكيكدة", nameFr: "Algérie - Skikda", activeFires: 1, satelliteHotspots: 1, severity: "high", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سيدي بلعباس", nameFr: "Algérie - Sidi Bel Abbès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عنابة", nameFr: "Algérie - Annaba", activeFires: 1, satelliteHotspots: 0, severity: "medium", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - قالمة", nameFr: "Algérie - Guelma", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - قسنطينة", nameFr: "Algérie - Constantine", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - المدية", nameFr: "Algérie - Médéa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - مستغانم", nameFr: "Algérie - Mostaganem", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - المسيلة", nameFr: "Algérie - M'Sila", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - معسكر", nameFr: "Algérie - Mascara", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - ورقلة", nameFr: "Algérie - Ouargla", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - وهران", nameFr: "Algérie - Oran", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - البيض", nameFr: "Algérie - El Bayadh", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - إليزي", nameFr: "Algérie - Illizi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - برج بوعريريج", nameFr: "Algérie - Bordj Bou Arréridj", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بومرداس", nameFr: "Algérie - Boumerdès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الطارف", nameFr: "Algérie - El Tarf", activeFires: 1, satelliteHotspots: 2, severity: "critical", evacuationRecommended: true, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تندوف", nameFr: "Algérie - Tindouf", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيسمسيلت", nameFr: "Algérie - Tissemsilt", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - الوادي", nameFr: "Algérie - El Oued", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - خنشلة", nameFr: "Algérie - Khenchela", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - سوق أهراس", nameFr: "Algérie - Souk Ahras", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيبازة", nameFr: "Algérie - Tipaza", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - ميلة", nameFr: "Algérie - Mila", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عين الدفلى", nameFr: "Algérie - Aïn Defla", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - النعامة", nameFr: "Algérie - Naâma", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عين تموشنت", nameFr: "Algérie - Aïn Témouchent", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - غرداية", nameFr: "Algérie - Ghardaïa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - غليزان", nameFr: "Algérie - Relizane", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تيميمون", nameFr: "Algérie - Timimoun", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - برج باجي مختار", nameFr: "Algérie - Bordj Badji Mokhtar", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - أولاد جلال", nameFr: "Algérie - Ouled Djellal", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - بني عباس", nameFr: "Algérie - Béni Abbès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عين صالح", nameFr: "Algérie - In Salah", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - عين قزام", nameFr: "Algérie - In Guezzam", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - تقرت", nameFr: "Algérie - Touggourt", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - جانت", nameFr: "Algérie - Djanet", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - المغير", nameFr: "Algérie - El M'Ghair", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "الجزائر - المنيعة", nameFr: "Algérie - El Meniaa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "1021" },
  { nameAr: "تونس - جندوبة", nameFr: "Tunisie - Jendouba", activeFires: 1, satelliteHotspots: 1, severity: "critical", evacuationRecommended: true, emergencyPhone: "198" },
  { nameAr: "تونس - باجة", nameFr: "Tunisie - Béja", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - بنزرت", nameFr: "Tunisie - Bizerte", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - تونس العاصمة", nameFr: "Tunisie - Tunis", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - أريانة", nameFr: "Tunisie - Ariana", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - بن عروس", nameFr: "Tunisie - Ben Arous", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - منوبة", nameFr: "Tunisie - Manouba", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - نابل", nameFr: "Tunisie - Nabeul", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - زغوان", nameFr: "Tunisie - Zaghouan", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - الكاف", nameFr: "Tunisie - Le Kef", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - سليانة", nameFr: "Tunisie - Siliana", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - سوسة", nameFr: "Tunisie - Sousse", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - المنستير", nameFr: "Tunisie - Monastir", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - المهدية", nameFr: "Tunisie - Mahdia", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - صفاقس", nameFr: "Tunisie - Sfax", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - القيروان", nameFr: "Tunisie - Kairouan", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - القصرين", nameFr: "Tunisie - Kasserine", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - سيدي بوزيد", nameFr: "Tunisie - Sidi Bouzid", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - قابس", nameFr: "Tunisie - Gabès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - مدنين", nameFr: "Tunisie - Medenine", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - تطاوين", nameFr: "Tunisie - Tataouine", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - قفصة", nameFr: "Tunisie - Gafsa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - توزر", nameFr: "Tunisie - Tozeur", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "تونس - قبلي", nameFr: "Tunisie - Kebili", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "198" },
  { nameAr: "المغرب - طنجة تطوان الحسيمة", nameFr: "Maroc - Tanger-Tétouan", activeFires: 1, satelliteHotspots: 1, severity: "high", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - الشرقية", nameFr: "Maroc - L'Oriental", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - فاس مكناس", nameFr: "Maroc - Fès-Meknès", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - الرباط سلا القنيطرة", nameFr: "Maroc - Rabat-Salé-Kénitra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - بني ملال خنيفرة", nameFr: "Maroc - Béni Mellal-Khénifra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - الدار البيضاء سطات", nameFr: "Maroc - Casablanca-Settat", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - مراكش آسفي", nameFr: "Maroc - Marrakech-Safi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - درعة تافيلالت", nameFr: "Maroc - Drâa-Tafilalet", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - سوس ماسة", nameFr: "Maroc - Souss-Massa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - كلميم واد نون", nameFr: "Maroc - Guelmim-Oued Noun", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - العيون الساقية الحمراء", nameFr: "Maroc - Laâyoune-Sakia El Hamra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "المغرب - الداخلة وادي الذهب", nameFr: "Maroc - Dakhla-Oued Ed-Dahab", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "150" },
  { nameAr: "ليبيا - الجبل الأخضر", nameFr: "Libye - Al Jabal al Akhdar", activeFires: 1, satelliteHotspots: 1, severity: "medium", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - طرابلس", nameFr: "Libye - Tripoli", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - بنغازي", nameFr: "Libye - Benghazi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - مصراتة", nameFr: "Libye - Misrata", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الزاوية", nameFr: "Libye - Zawiya", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - سبها", nameFr: "Libye - Sabha", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - سرت", nameFr: "Libye - Sirte", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - طبرق", nameFr: "Libye - Tobruk", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - درنة", nameFr: "Libye - Derna", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - المرج", nameFr: "Libye - Al Marj", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الواحات", nameFr: "Libye - Al Wahat", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الكفرة", nameFr: "Libye - Al Kufra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - مرزق", nameFr: "Libye - Murzuq", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - غات", nameFr: "Libye - Ghat", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - وادي الحياة", nameFr: "Libye - Wadi al Hayaa", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - وادي الشاطئ", nameFr: "Libye - Wadi al Shatii", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الجفرة", nameFr: "Libye - Al Jufra", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الجبل الغربي", nameFr: "Libye - Jabal al Gharbi", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - نالوت", nameFr: "Libye - Nalut", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - النقاط الخمس", nameFr: "Libye - Nuqat al Khams", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - الجفارة", nameFr: "Libye - Al Jfara", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
  { nameAr: "ليبيا - المرقب", nameFr: "Libye - Al Murgub", activeFires: 0, satelliteHotspots: 0, severity: "safe", evacuationRecommended: false, emergencyPhone: "193" },
];
